test:
	g++ -g -Wfatal-errors --std=c++20 -I. -I../thirdparty/ -I../thirdparty/eigen-3.4.0/  -I../thirdparty/statslib/include -I../thirdparty/gcem/include -I../include/ tests.cpp -o test_stats -lgsl
	./test_stats