name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install libgsl-dev
      run: sudo apt install libgsl-dev
    - name: make test
      working-directory: ./tests/
      run: make test
